tutorial/accounts/urls.py
from django.conf.urls import url
from .import views
from django.contrib.auth import views as auth_views
from django.urls import reverse, reverse_lazy, resolve


app_name="accounts"

urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    url(r'^reset-password/$', auth_views.PasswordResetView.as_view(
        template_name='accounts/reset_password.html',
        success_url = reverse_lazy('accounts:password_reset_done'),
        email_template_name ='accounts/reset_password_email.html'),
        {'email_template_name':'accounts/reset_password_email.html'},
        name='password_reset'),
    url(r'^reset-password/done/$', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/reset_password_confirm.html',
        success_url = reverse_lazy('accounts:password_reset_complete')
    ), name='password_reset_confirm'),
    url(r'^reset-password/complete/$', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name = 'password_reset_complete')
]

tutorial/home/urls.py
from django.conf.urls import url
from home.views import HomeView

app_name="home"


urlpatterns = [
    url(r'^$',HomeView.as_view(), name = 'home')
]

tutorial/tutorial/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from .import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^home/', include('home.urls', namespace='home'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutorial/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.


class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager, self).get_queryset().filter(city='London')


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete='')
    description = models.CharField(max_length=1000, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image', blank=True)


    london=UserProfileManager()

    def __str__(self):
        return self.user.username

    def create_profile(sender, **kwargs):
        if kwargs['created']:
            user_profile = UserProfile.objects.create(user=kwargs['instance'])

    post_save.connect(create_profile, sender=User)

tutorial/home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post (models.Model):
     post = models.CharField(max_length = 500)
     user = models.ForeignKey(User, on_delete=True)
     created = models.DateTimeField(auto_now_add = True)
     updated = models.DateTimeField(auto_now = True)

tutorial/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = {
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        }

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class EditProfileForm(UserChangeForm):

        class Meta:
            model = User
            fields = {
                'email',
                'first_name',
                'last_name',
                'password'
            }

tutorial/home/forms.py
from django import forms
from home.models import Post

class HomeForm(forms.ModelForm):
    post = forms.CharField(widget=forms.TextInput(
        attrs={
            "class":"form-control",
            "placeholder":"Write a post",
        }
    ))

    class Meta:
        model = Post
        fields = ('post',)

tutorial/accounts/views.py
from django.shortcuts import render, redirect
from accounts.forms import (
    RegistrationForm,
    EditProfileForm,
)
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
# Create your views here.


def register(request):
    if request.method=='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/account')
    else:
        form = RegistrationForm()
        args = {'form': form}
    return render(request, 'accounts/reg_form.html', args)


def view_profile(request):
    args = {'user': request.user}
    return render(request, 'accounts/profile.html', args)


def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('/account/profile')
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form':form}
        return render(request, 'accounts/edit_profile.html', args)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/account/profile')
        else:
            return redirect('/account/change-password')

    else:
        form = PasswordChangeForm(user=request.user)

        args={'form': form}
        return render(request, 'accounts/change_password.html', args)

tutorial/home/views.py
from django.views.generic import TemplateView
from home.forms import HomeForm
from django.shortcuts import render
from home.models import Post
from django.contrib.auth.models import User


class HomeView(TemplateView):
    template_name = 'home/home.html'

    def get(self,request):
        form = HomeForm()
        posts = Post.objects.all().order_by('-created')
        users = User.objects.all()
        args = {'form':form, 'posts':posts,'users':users}
        return render(request, self.template_name,args)

    def post(self,request):
        form = HomeForm(request.POST)
        if form.is_valid():
            post = form.save(commit = False)
            post.user = request.user
            post.save()
            form.save()
            text = form.cleaned_data['post']
            form = HomeForm()
        args = {'form':form, 'text':text}
        return render(request, self.template_name, args)

tutorial/tutorial/views.py
from django.shortcuts import redirect


def login_redirect(request):
    return redirect('/account/login')

tutorial/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block head %}
<title>Profile</title>
{% endblock %}
{% block body %}
<div class="container">
 <form method="post">
     {% csrf_token %}
     {{ form.as_p }}
     <button type="submit">Submit</button>
 </form>
</div>
{% endblock %}

tutorial/accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% block head %}
<title>Profile</title>
{% endblock %}
{% block body %}
<div class="container">
 <form method="post">
     {% csrf_token %}
     {{ form.as_p }}
     <button type="submit">Submit</button>
 </form>
</div>
{% endblock %}

tutorial/accounts/templates/accounts/login.html
 {% extends 'base.html' %}
 {% block body %}
 <div class="container">
     <h1>Welcome</h1>
     <p>
         You can log in here!
     </p>
     <h2>Login</h2>
     <form method="post">
         {% csrf_token  %}
         {{ form.as_p }}
         <button  type="submit">Login</button>
     </form>
 </div>
 {% endblock %}

tutorial/accounts/templates/accounts/logout.html
 {% extends 'base.html' %}
 {% block body %}
 <div class="container">
     <h1>Welcome</h1>
     <p>
         You have log out!
     </p>
 </div>
 {% endblock %}

tutorial/accounts/templates/accounts/password_reset_complete.html
   {% extends 'base.html' %}
 {% block body %}
 <div class="container">
     <h1>Password reset succesifully</h1>
     <p>
         You reset your password successifully !
     </p>
     <a href="{% url 'accounts:login' %}">Login</a>
 </div>
 {% endblock %}

tutorial/accounts/templates/accounts/password_reset_done.html
   {% extends 'base.html' %}
 {% block body %}
 <div class="container">
     <h1>Password reset done</h1>
     <p>
         You have reset your password succesifully
     </p>
 </div>
 {% endblock %}

tutorial/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block head %}
<title>Profile</title>
{% endblock %}
{% block body %}
<div class="container">
    <p>

        Firstname: {{ user.first_name }}<br>
        Lastname: {{ user.last_name }}<br>
        Description: {{user.userprofile.description }}
    </p>
        <img src="{{ user.userprofile.image.url }}" width="240">
</div>
{% endblock %}

tutorial/accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">Submit</button>
</form>
</div>
{% endblock %}

tutorial/accounts/templates/accounts/reset_password.html
  {% extends 'base.html' %}
 {% block body %}
 <div class="container">
     <h1>Password reset</h1>
     <p>
         You can reset your password here !
     </p>
     <form method="post">
         {% csrf_token  %}
         {{ form.as_p }}
         <button  type="submit">Reset Password</button>
     </form>
 </div>
 {% endblock %}

tutorial/accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">Submit</button>
</form>
</div>
{% endblock %}

tutorial/accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}
{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}	{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}
{% trans "Thanks for using our site!" %}
{% blocktrans %}The {{ site_name }} team{% endblocktrans %}
{% endautoescape %}

tutorial/accounts/templates/base.html
<!DOCTYPE html>
<html>
    <head>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <meta name="viewport" content="width = device-width, initial-scale=1.0"
        {% block head %}
        <meta charset="utf-8">
        <title>Base</title>
        {% endblock %}
    </head>
    <body>

 <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample10" aria-controls="navbarsExample10" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample10">
            {% if user.is_authenticated %}
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="/"> Social Network <span class="sr-only">(current)</span></a>
            </li>
              <li class="nav-item" >
                  <a class="nav-link disabled" href="{% url 'home:home' %}">Home</a>
              </li>
              <li class="nav-item" >
                  <a class="nav-link disabled" href="{% url 'accounts:logout' %}">Logout</a>
              </li>
              <li class="nav-item" >
                  <a class="nav-link disabled" href="{% url 'accounts:view_profile' %}">Profile</a>
              </li>
              <li class="nav-item" >
                  <a class="nav-link disabled" href="{% url 'accounts:edit_profile' %}">Edit Profile</a>
              </li>
              <li class="nav-item" >
                  <a class="nav-link disabled" href="{% url 'accounts:change_password' %}">Change Password</a>
              </li>
          </ul>
            {% else %}
            <ul class="nav navbar-nav">
                 <li class="nav-item" >
                  <a class="nav-link disabled" href="{% url 'accounts:password_reset' %}">Reset Password</a>
              </li>
            </ul>
             <ul class="navbar-nav">
              <li class="nav-item" >
                  <a class="nav-link disabled" href="{% url 'accounts:home' %}">Home</a>
              </li>
              <li class="nav-item" >
                  <a class="nav-link disabled" href="{% url 'accounts:login' %}">Login</a>
              </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="{% url 'accounts:register' %}">Register</a>
            </li>
          </ul>
            {% endif %}
        </div>
      </nav>
        {% block body %}
        {% endblock %}
    </body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</html>

tutorial/home/templates/home/home.html
{% extends 'base.html' %}

{% block body %}
<div class = "container">
    <div class="col-md-8">
<h2>Home</h2>
<form method="post">
    {% csrf_token %}
    {{ form.post }}
    <br>
    <button type="submit">Submit</button>
</form>
<h2>{{ text }}</h2>
{% for post in posts %}
<h2>{{ post.post }}</h2>
<h2>{{post.created }}</h2>
{% endfor %}
</div>
    <div class = "col-md-4">
        <h2>Other People</h2>
        {% for user in users %}
        <a href="{% url 'accounts:view_profile' %}">
       <h3>  {{ user.username }} </h3>
            </a>
        {% endfor %}
    </div>
</div>
{% endblock %}